# frozen_string_literal: true

source 'https://rubygems.org'

gem 'html2rss', git: 'https://github.com/html2rss/html2rss.git', branch: 'feat/registry-v1'

group :development do
  gem 'nokogiri'
  gem 'public_suffix'
  gem 'rspec', '~> 3.0'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
end
