# frozen_string_literal: true

source 'https://rubygems.org'

gem 'html2rss', path: '../../html2rss'

group :development do
  gem 'nokogiri'
  gem 'public_suffix'
  gem 'rspec', '~> 3.0'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
end
