name: Ruby

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUNDLE_GEMFILE: tool/Gemfile

jobs:
  ready:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -yqq yamllint

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
          working-directory: tool

      - name: Run quality gate
        run: make ready

  test_changed_configs:
    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: tool/Gemfile

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
          working-directory: tool

      - name: setup remote origin
        run: >-
          git remote set-url origin
          https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Test changed configs with fetching
        run: |
          git fetch origin master --depth 1
          make test-fetch-changed-configs
